print("LUCAS GABRYEL MONTEIRO DE LIMA")

from Estudo import Arvore
arvore = Arvore()
print("Adicionando 20, 10, 30, 40 e 5  ")
arvore.add(20)
arvore.add(10)
arvore.add(30)
arvore.add(40)
arvore.add(5)
arvore.imprimir()

s = arvore.soma()
a = arvore.alturaTree()
c = arvore.sucessor()
d = arvore.predecessor()
e = arvore.totalElementos()
print("A SOMA DE TODOS OS ELEMENTOS = {}" .format(s))
print("A ÁRVORE TEM TAMANHO = {}" .format(a))
print("O SUSCESSOR DA ÁRVORE = {}" .format(c))
print("O PREDECESSOR DA ÁRVORE = {}" .format(d))
print("A ÁRVORE CONTEM = {}" .format(e) + " ELEMENTOS")
r = arvore.remover(10)
print("APÓS REMOÇÃO A ÁRVORE FICOU COM ESSE FORMATO")
arvore.imprimir()
g = arvore.elemDoNivel(1)
print("OS ELEMENTOS DO NÍVEL 1 SÃO: {}" .format(g))
print("FALTOU FAZER O BALANCIAMENTO...")
